ignoreFiles:
    - node_modules/**/*
    - packages/**/node_modules/**/*
    - dist/**/*
    - public/**/*

rules:
    color-no-invalid-hex:
        - true
        - severity: error
    font-family-no-duplicate-names:
        - true
        - severity: warning
    font-family-no-missing-generic-family-keyword:
        - true
        - severity: warning
    function-calc-no-unspaced-operator:
        - true
        - severity: error
    function-linear-gradient-no-nonstandard-direction:
        - true
        - severity: warning
    string-no-newline:
        - true
        - severity: error
    unit-no-unknown:
        - true
        - severity: error
    property-no-unknown:
        - true
        - severity: error
    keyframe-declaration-no-important:
        - true
        - severity: warning
    declaration-block-no-duplicate-properties:
        - true
        - severity: warning
    declaration-block-no-shorthand-property-overrides:
        - true
        - severity: warning
    block-no-empty:
        - true
        - severity: warning
    selector-pseudo-class-no-unknown:
        - true
        - severity: error
    selector-pseudo-element-no-unknown:
        - true
        - severity: error
    selector-type-no-unknown:
        - false
    media-feature-name-no-unknown:
        - true
        - severity: error
    at-rule-no-unknown:
        -
            - true
            - ignoreAtRules:
                - mixin
                - include
        - severity: error
    comment-no-empty:
        - true
        - severity: warning
    no-descending-specificity:
        - true
        - severity: warning
    no-duplicate-at-import-rules:
        - true
        - severity: warning
    no-duplicate-selectors:
        - true
        - severity: warning
    no-empty-source:
        - true
        - severity: warning
    no-extra-semicolons:
        - true
        - severity: warning
    no-invalid-double-slash-comments:
        - true
        - severity: warning
    color-named:
        -
            - 'never'
    color-no-hex: false
    function-url-no-scheme-relative: false
    keyframes-name-pattern: false
    time-min-milliseconds:
        -
            - 0.0001
        - severity: warning
    shorthand-property-no-redundant-values: false
    value-no-vendor-prefix:
        - true
        - severity: warning
    custom-property-pattern: false
    property-no-vendor-prefix:
        -
            - true
            - ignoreProperties:
                - -webkit-overflow-scrolling
                - -webkit-line-clamp
        - severity: warning
    declaration-block-no-redundant-longhand-properties: false
    declaration-no-important:
        - true
        - severity: warning
    declaration-block-single-line-max-declarations:
        - 1
        - severity: warning
    selector-max-empty-lines:
        -
            - 0
        - severity: warning
    media-feature-name-no-vendor-prefix:
        - true
        - severity: warning
    at-rule-no-vendor-prefix:
        - true
        - severity: warning
    max-nesting-depth:
        - false
    no-unknown-animations:
        - false
    color-hex-case:
        -
            - lower
        - severity: warning
    color-hex-length:
        - false
    font-family-name-quotes:
        -
            - always-unless-keyword
        - severity: warning
    font-weight-notation:
        - false
    function-comma-newline-after:
        - false
    function-comma-newline-before:
        -
            - never-multi-line
        - severity: warning
    function-comma-space-after:
        -
            - always-single-line
        - severity: warning
    function-comma-space-before:
        -
            - never
        - severity: warning
    function-max-empty-lines:
        -
            - 0
        - severity: warning
    function-name-case:
        -
            - lower
        - severity: warning
    function-parentheses-newline-inside:
        -
            - always-multi-line
        - severity: warning
    function-parentheses-space-inside:
        -
            - never-single-line
        - severity: warning
    function-url-quotes:
        -
            - always
        - severity: warning
    function-whitespace-after:
        -
            - always
        - severity: warning
    number-leading-zero:
        - false
    number-no-trailing-zeros:
        - true
        - severity: warning
    string-quotes:
        -
            - single
        - severity: warning
    length-zero-no-unit:
        - true
        - severity: warning
    unit-case:
        -
            - lower
        - severity: warning
    value-keyword-case:
        -
            - lower
        - severity: warning
    value-list-comma-newline-after:
        -
            - never-multi-line
        - severity: warning
    value-list-comma-newline-before:
        -
            - never-multi-line
        - severity: warning
    value-list-comma-space-after:
        -
            - always
        - severity: warning
    value-list-comma-space-before:
        -
            - never
        - severity: warning
    value-list-max-empty-lines:
        -
            - 0
        - severity: warning
    custom-property-empty-line-before:
        - false
    property-case:
        -
            - lower
        - severity: warning
    declaration-bang-space-after:
        -
            - never
        - severity: warning
    declaration-bang-space-before:
        -
            - always
        - severity: warning
    declaration-colon-newline-after:
        - false
    declaration-colon-space-after:
        -
            - always
        - severity: warning
    declaration-colon-space-before:
        -
            - never
        - severity: warning
    declaration-empty-line-before:
        - false
    declaration-block-semicolon-newline-after:
        - false
    declaration-block-semicolon-newline-before:
        -
            - never
        - severity: warning
    declaration-block-semicolon-space-after:
        -
            - always
        - severity: warning
    declaration-block-semicolon-space-before:
        -
            - never
        - severity: warning
    declaration-block-trailing-semicolon:
        -
            - always
        - severity: warning
    block-closing-brace-empty-line-before:
        -
            - never
        - severity: warning
    block-closing-brace-newline-after:
        -
            - always
        - severity: warning
    block-closing-brace-newline-before:
        -
            - never-multi-line
        - severity: warning
    block-closing-brace-space-after:
        -
            - always-single-line
        - severity: warning
    block-closing-brace-space-before:
        -
            - always-single-line
        - severity: warning
    block-opening-brace-newline-after:
        -
            - always-multi-line
        - severity: warning
    block-opening-brace-newline-before:
        -
            - never
        - severity: warning
    block-opening-brace-space-after:
        -
            - always-single-line
        - severity: warning
    block-opening-brace-space-before:
        -
            - always
        - severity: warning
    selector-attribute-brackets-space-inside:
        -
            - never
        - severity: warning
    selector-attribute-operator-space-after:
        -
            - never
        - severity: warning
    selector-attribute-operator-space-before:
        -
            - never
        - severity: warning
    selector-attribute-quotes:
        -
            - always
        - severity: warning
    selector-combinator-space-after:
        -
            - always
        - severity: warning
    selector-combinator-space-before:
        -
            - always
        - severity: warning
    selector-descendant-combinator-no-non-space:
        - true
        - severity: warning
    selector-pseudo-class-case:
        -
            - lower
        - severity: warning
    selector-pseudo-class-parentheses-space-inside:
        -
            - never
        - severity: warning
    selector-pseudo-element-case:
        -
            - lower
        - severity: warning
    selector-pseudo-element-colon-notation:
        -
            - double
        - severity: warning
    selector-type-case:
        -
            - lower
        - severity: warning
    selector-list-comma-newline-after:
        -
            - always-multi-line
        - severity: warning
    selector-list-comma-newline-before:
        -
            - never-multi-line
        - severity: warning
    selector-list-comma-space-after:
        -
            - always-single-line
        - severity: warning
    selector-list-comma-space-before:
        -
            - never
        - severity: warning
    rule-empty-line-before:
        -
            - always-multi-line
            - except:
                - after-single-line-comment
                - inside-block-and-after-rule
                - first-nested
    media-feature-colon-space-after:
        -
            - always
        - severity: warning
    media-feature-colon-space-before:
        -
            - never
        - severity: warning
    media-feature-name-case:
        -
            - lower
        - severity: warning
    media-feature-parentheses-space-inside:
        -
            - never
        - severity: warning
    media-feature-range-operator-space-after:
        -
            - always
        - severity: warning
    media-feature-range-operator-space-before:
        -
            - always
        - severity: warning
    media-query-list-comma-newline-after:
        -
            - always-multi-line
        - severity: warning
    media-query-list-comma-newline-before:
        -
            - never-multi-line
        - severity: warning
    media-query-list-comma-space-after:
        -
            - always-single-line
        - severity: warning
    media-query-list-comma-space-before:
        -
            - never
        - severity: warning
    at-rule-empty-line-before:
        -
            - always
            - except:
                - after-same-name
                - first-nested
            - ignore:
                - after-comment
                - blockless-after-same-name-blockless
        - severity: warning
    at-rule-name-case:
        -
            - lower
        - severity: warning
    at-rule-name-newline-after:
        -
            - always-multi-line
        - severity: warning
    at-rule-name-space-after:
        -
            - always-single-line
        - severity: warning
    at-rule-semicolon-newline-after:
        -
            - always
        - severity: warning
    at-rule-semicolon-space-before:
        -
            - never
        - severity: warning
    comment-empty-line-before:
        -
            - always
        - severity: warning
    comment-whitespace-inside:
        -
            - always
        - severity: warning
    indentation:
        - 4
        - severity: warning
    max-empty-lines:
        -
            - 1
            - ignore:
                - comments
        - severity: warning
    max-line-length:
        - false
    no-eol-whitespace:
        - true
        - severity: warning
    no-missing-end-of-source-newline:
        - true
        - severity: warning
